# .github/workflows/cypress.yml

name: E2E Tests with Cypress

on:
  push:
    branches: 
      - main
      - feat/**
  pull_request:
    branches: 
      - main
      - feat/**

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Start Angular app
        run: npm run start &

      - name: Wait for Angular app to be ready
        run: npx wait-on http://localhost:4200

      - name: Run Cypress tests
        run: npm run cy:run