---
# .github/workflows/cypress.yml
name: E2E Tests (Cypress)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress installation
        run: npm run cy:verify

      - name: Run Cypress tests headlessly
        run: npm run cy:run
